-- DROP DATABASE IF EXISTS BarcBees;
-- CREATE DATABASE BarcBees;
-- USE BarcBees;
DROP TABLE IF EXISTS UserHives;
DROP TABLE IF EXISTS HiveData;
DROP TABLE IF EXISTS Temperature;
DROP TABLE IF EXISTS OutsidePressure;
DROP TABLE IF EXISTS OutsideTemp;
DROP TABLE IF EXISTS Notify;
DROP TYPE  IF EXISTS notifType;
DROP TABLE IF EXISTS CarbonDioxide;
DROP TABLE IF EXISTS Humidity;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Hive;


CREATE TABLE Hive(
	hiveID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(100) not null,
    zipcode char(5) not null,
    startDate datetime not null,
    passkey char(100) not null
);

CREATE TABLE Users(
    userID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    username varchar(20) NOT NULL,
	password varchar(500) NOT NULL,
	email varchar(500) NOT NULL,
    phone char(10) NULL,
    sessionToken varchar(500) NULL,
    dataStartDate TIMESTAMP NULL 
);

CREATE TYPE notifType AS ENUM('email','phone','both', 'none');

CREATE TABLE Notify(
    userID int PRIMARY KEY references Users(userID),
    notifType notifType,
    temp boolean,
    humidity boolean,
    carbonDioxide boolean,
    swarm boolean
);


CREATE TABLE Temperature(
    tempID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hiveID int NOT NULL  references Hive(hiveID),
    timestamp TIMESTAMP NOT NULL,
    reading float NULL
);

CREATE TABLE OutsideTemp(
    oTempID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hiveID int NOT NULL references Hive(hiveID),
    timestamp TIMESTAMP NOT NULL,
    reading float NULL
);

CREATE TABLE CarbonDioxide(
    carbonDioxideID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hiveID int NOT NULL  references Hive(hiveID),
    timestamp TIMESTAMP NOT NULL,
    reading float NULL
);

CREATE TABLE Humidity(
    humidtyID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hiveID int NOT NULL  references Hive(hiveID),
    timestamp TIMESTAMP NOT NULL ,
    reading float NULL
);

CREATE TABLE OutsidePressure(
    pressureID int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hiveID int NOT NULL  references Hive(hiveID),
    timestamp TIMESTAMP NOT NULL,
    reading float NULL
);


CREATE TABLE HiveData(
	hiveID int NOT NULL references Hive(hiveID),
    timestamp TIMESTAMP NOT NULL ,
    tempID int NULL references Temperature(tempID),
    humidtyID int NULL references Humidity(humidtyID),
    oTempID int NULL references OutsideTemp(oTempID),
    pressureID int NULL references OutsidePressure(pressureID),
    carbonDioxideID int NULL references carbonDioxide(carbonDioxideID),
    PRIMARY KEY (hiveID, timestamp)
);

CREATE TABLE UserHives(
    userID int NOT NULL references Users(userID),
    hiveID int NOT NULL references Hive(hiveID),
    PRIMARY KEY(userID, hiveID)
);

