DROP TABLE IF EXISTS userhives;
DROP TABLE IF EXISTS hivedata;
DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS outsidepressure;
DROP TABLE IF EXISTS outsidetemp;
DROP TABLE IF EXISTS notify;
DROP TABLE IF EXISTS carbondioxide;
DROP TABLE IF EXISTS humidity;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS hive;
DROP TYPE IF EXISTS notif_type;

CREATE TABLE hive (
  hiveid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  zipcode CHAR(5) NOT NULL,
  startdate TIMESTAMPTZ NOT NULL,
  passkey VARCHAR(100) NOT NULL
);

CREATE TABLE users (
  userid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(500) NOT NULL,
  email VARCHAR(500) NOT NULL UNIQUE,
  phone CHAR(10),
  sessiontoken VARCHAR(500),
  datastartdate TIMESTAMPTZ
);

CREATE TYPE notif_type AS ENUM ('email', 'phone', 'both', 'none');

CREATE TABLE notify (
  userid INTEGER PRIMARY KEY REFERENCES users(userid),
  notiftype notif_type NOT NULL DEFAULT 'none',
  temp BOOLEAN NOT NULL DEFAULT FALSE,
  humidity BOOLEAN NOT NULL DEFAULT FALSE,
  carbondioxide BOOLEAN NOT NULL DEFAULT FALSE,
  swarm BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE temperature (
  tempid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hiveid INTEGER NOT NULL REFERENCES hive(hiveid),
  timestamp TIMESTAMPTZ NOT NULL,
  reading DOUBLE PRECISION,
  UNIQUE (hiveid, timestamp)
);

CREATE TABLE outsidetemp (
  otempid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hiveid INTEGER NOT NULL REFERENCES hive(hiveid),
  timestamp TIMESTAMPTZ NOT NULL,
  reading DOUBLE PRECISION,
  UNIQUE (hiveid, timestamp)
);

CREATE TABLE carbondioxide (
  carbondioxideid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hiveid INTEGER NOT NULL REFERENCES hive(hiveid),
  timestamp TIMESTAMPTZ NOT NULL,
  reading DOUBLE PRECISION,
  UNIQUE (hiveid, timestamp)
);

CREATE TABLE humidity (
  humidityid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hiveid INTEGER NOT NULL REFERENCES hive(hiveid),
  timestamp TIMESTAMPTZ NOT NULL,
  reading DOUBLE PRECISION,
  UNIQUE (hiveid, timestamp)
);

CREATE TABLE outsidepressure (
  pressureid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hiveid INTEGER NOT NULL REFERENCES hive(hiveid),
  timestamp TIMESTAMPTZ NOT NULL,
  reading DOUBLE PRECISION,
  UNIQUE (hiveid, timestamp)
);

CREATE TABLE hivedata (
  hiveid INTEGER NOT NULL REFERENCES hive(hiveid),
  timestamp TIMESTAMPTZ NOT NULL,
  tempid INTEGER REFERENCES temperature(tempid),
  humidityid INTEGER REFERENCES humidity(humidityid),
  otempid INTEGER REFERENCES outsidetemp(otempid),
  pressureid INTEGER REFERENCES outsidepressure(pressureid),
  carbondioxideid INTEGER REFERENCES carbondioxide(carbondioxideid),
  PRIMARY KEY (hiveid, timestamp)
);

CREATE TABLE userhives (
  userid INTEGER NOT NULL REFERENCES users(userid),
  hiveid INTEGER NOT NULL REFERENCES hive(hiveid),
  PRIMARY KEY (userid, hiveid)
);
